server{
    listen 80;

    root /app;
    index index.html;

    location /board {
        alias /app/pages/board/;
        index index.html;
    }

    location /partners {
        alias /app/pages/partners/;
        index index.html;
    }

    location /titelan {
        alias /app/pages/titelan/;
        index index.html;
    }
}

