server{
    listen 80;

    root /app;
    index index.html;

    # Finnish pages
    location /membership {
        alias /app/pages/membership/;
    }

    location /events {
        alias /app/pages/events/;
    }

    location /titelan {
        alias /app/pages/titelan/;
    }

    location /products {
        alias /app/pages/products/;
    }

    location /partners {
        alias /app/pages/partners/;
    }

    location /association {
        alias /app/pages/association/;
    }

    location /board {
        alias /app/pages/board/;
    }

    location /contact {
        alias /app/pages/contact/;
    }

    # English pages
    location /en/ {
        alias /app/;
    }
    location /en/membership {
        alias /app/pages/membership/;
    }

    location /en/events {
        alias /app/pages/events/;
    }

    location /en/titelan {
        alias /app/pages/titelan/;
    }

    location /en/products {
        alias /app/pages/products/;
    }

    location /en/partners {
        alias /app/pages/partners/;
    }

    location /en/association {
        alias /app/pages/association/;
    }

    location /en/board {
        alias /app/pages/board/;
    }

    location /en/contact {
        alias /app/pages/contact/;
    }
}

