server{
    listen 80;

    root /app;
    index index.html;

    # Finnish pages
    location /partners {
        alias /app/pages/partners/;
    }

    location /events {
        alias /app/pages/events/;
    }

    location /titelan {
        alias /app/pages/titelan/;
    }

    location /students {
        alias /app/pages/students/;
    }

    location /about {
        alias /app/pages/about/;
    }

    location /contact {
        alias /app/pages/contact/;
    }

    # English pages
    location /en {
        alias /app/;
    }

    location /en/partners {
        alias /app/pages/partners/;
    }

    location /en/events {
        alias /app/pages/events/;
    }

    location /en/titelan {
        alias /app/pages/titelan/;
    }

    location /en/students {
        alias /app/pages/students/;
    }

    location /en/about {
        alias /app/pages/about/;
    }

    location /en/contact {
        alias /app/pages/contact/;
    }
}

